language: sass

notifications:
  irc:
    channels:
      - "irc.esper.net#kurisu"
    template:
      - "%{repository} (%{commit}) {branch}"
      - "%{author} %{message}"
    use_notice: true
    skip_join: true